// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD58rR7AKOslJvNIEWCtu1cxmzf0in_fJA',
    appId: '1:412924601581:web:c29342ce27b3c47eb398e4',
    messagingSenderId: '412924601581',
    projectId: 'desafionatacaounaerp',
    authDomain: 'desafionatacaounaerp.firebaseapp.com',
    storageBucket: 'desafionatacaounaerp.appspot.com',
    measurementId: 'G-PG11954SS6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2th3i0xCd9AbO9Sj-hr18jFfb5R8YmIg',
    appId: '1:412924601581:android:8031bc38c3a1f378b398e4',
    messagingSenderId: '412924601581',
    projectId: 'desafionatacaounaerp',
    storageBucket: 'desafionatacaounaerp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9yNGfl-kLbH2NFB-xy-Jf85oK143IJNI',
    appId: '1:412924601581:ios:5eb298d58435c104b398e4',
    messagingSenderId: '412924601581',
    projectId: 'desafionatacaounaerp',
    storageBucket: 'desafionatacaounaerp.appspot.com',
    iosBundleId: 'br.rigoliveira.desafio6Etapa',
  );
}
